
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-ArticlesTableComponent","number":70,"title":"Table Component for Articles plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/70"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-ArticlesFormComponent","number":69,"title":"Form Component for Articles plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/69"},{"author":{"id":"U_kgDOBXmKFg","is_bot":false,"login":"KyleWong288","name":"Kyle Wong"},"headRefName":"Kyle-UCSBOrganization-fixtures","number":68,"title":"added fixtures for UCSB Organization","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/68"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Ray-Recommendation-Fixtures","number":67,"title":"Ray - Create fixtures for Recommendation","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/67"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Ray-Recommendation-backend","number":66,"title":"Ray - Copy files for Backend CRUD API Recommendation from team02 ","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/66"}]
