
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequest-Table","number":80,"title":"Table Component and Testing for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/80"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequest-Form","number":79,"title":"Help Request Form Component - Implementation and Testing","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/79"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequest-Fixtures","number":78,"title":"Create Fixtures for HelpRequests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/78"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequest-CRUD","number":77,"title":"Copied Files for HelpRequest for CRUD Backend","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/77"},{"author":{"id":"U_kgDOBXmKFg","is_bot":false,"login":"KyleWong288","name":"Kyle Wong"},"headRefName":"Kyle-UCSBOrganization-component","number":76,"title":"Added ucsb organization form component","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/76"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-ArticlesEdit","number":74,"title":"Edit Page for Articles plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/74"}]
