
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-PR-In-Review","number":62,"title":"A0 - PR In Review","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/62"}]
