
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBXmKFg","is_bot":false,"login":"KyleWong288","name":"Kyle Wong"},"headRefName":"Kyle-UCSBOrganization-component","number":75,"title":"added ucsb organization form component","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/75"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-ArticlesEdit","number":74,"title":"Edit Page for Articles plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/74"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-ArticlesIndex","number":73,"title":"Index Page for Articles plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/73"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-ArticlesCreate","number":72,"title":"Create Page for Articles plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/72"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-ArticlesPlaceholder","number":71,"title":"Copy Placeholders for Articles pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/71"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-ArticlesTableComponent","number":70,"title":"Table Component for Articles plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/70"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-ArticlesFormComponent","number":69,"title":"Form Component for Articles plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/69"}]
