
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBXjycA","is_bot":false,"login":"huangderful","name":""},"headRefName":"rh-copyfiles-menuitemreview","number":86,"title":"rh - everything copied in","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/86"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"ModifyREADME","number":85,"title":"Adjust title and links in README.md","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/85"},{"author":{"id":"U_kgDOBXmKFg","is_bot":false,"login":"KyleWong288","name":"Kyle Wong"},"headRefName":"Kyle-UCSBOrganization-table","number":84,"title":"added table component for UCSBOrganization","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/84"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-Table-Component-for-UCSBDiningCommonsMenuItem-plus-tests","number":83,"title":"Tiger - Table Component for UCSBDiningCommonsMenuItem plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/83"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-Form-Component-for-UCSBDiningCommonsMenuItem-plus-tests","number":82,"title":"Tiger - Form Component for UCSBDiningCommonsMenuItem plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/82"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequest-Table","number":80,"title":"Table Component and Testing for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/80"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequest-Form","number":79,"title":"Help Request Form Component - Implementation and Testing","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/79"}]
