
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequest-IndexPage","number":109,"title":"Jonathan help request index page","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/109"},{"author":{"id":"U_kgDOBXmKFg","is_bot":false,"login":"KyleWong288","name":"Kyle Wong"},"headRefName":"Kyle-UCSBOrganization-indexpage","number":108,"title":"Kyle ucsb organization indexpage","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/108"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Ray-RecommendationCreatePage","number":107,"title":"Ray - Create Page for RecommendationRequest plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/107"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Ray-RecommendationRequestTable","number":97,"title":"Ray - Table Component for Recommendation plus tests ","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/97"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequest-CreatePage","number":94,"title":"Create Page for HelpRequests with tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/94"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequest-Placeholders","number":93,"title":"Copy Placeholders for HelpRequest pages and add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/93"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Ray-Recommendation-Fixtures","number":91,"title":"Ray - Form Component for Recommendation plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-2/pull/91"}]
